# Specify the version of the Docker Compose file format
# version: "3.9"

services:
  app:
    # Build the Docker image using the specified context (directory)
    build:
      context: .
      args:
        - DEV=true
    # Map port 8000 on the host to port 8000 on the container
    ports:
      - "8000:8000"
    # Mount the local 'app' directory to the '/app' directory in the container
    volumes:
      - ./app:/app
    # Run the Django development server
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: